name: Push to main

on:
  push:
    branches:
      - main

jobs:
  push_to_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to Main
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch --prune --unshallow
        git remote set-url origin https://github.com/red-runner/actionizer-beam.git
        git checkout main
        git pull origin main

        # Make your changes here
        line1="This is line 1 to be added."
        line2="This is line 2 to be added."
        echo -e "$line1\n$line2" >> README.md

        git add README.md
        git commit -m "Commit message"
        git push origin main
