name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  push_to_master:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push to Master
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch --prune --unshallow
        git remote set-url origin https://github.com/USERNAME/REPOSITORY.git
        git checkout master
        git pull origin master
        # Make your changes here
        git add .
        git commit -m "Commit message"
        git push https://${{ secrets.PAT }}@github.com/USERNAME/REPOSITORY.git HEAD:master
